# Generated by Django 5.2.15 on 2026-06-04 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('life', 'Assurance vie simplifiée'), ('death_disability', 'Décès-invalidité')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('premium_monthly', models.PositiveIntegerField(help_text='Prime mensuelle FCFA')),
                ('coverage_amount', models.PositiveIntegerField(help_text='Montant garanti FCFA')),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='insurance.insuranceproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
