# Generated by Django 5.2.15 on 2026-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproduct',
            name='coverage_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='premium_monthly',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insurancesubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée')], default='active', max_length=20),
        ),
    ]
