# Generated by Django 5.2.15 on 2026-06-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microcredits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'À payer'), ('paid', 'Payée'), ('late', 'En retard')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='microcredits.creditapplication')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['application', 'installment_number'],
                'unique_together': {('application', 'installment_number')},
            },
        ),
    ]
