# Generated by Django 5.2.15 on 2026-06-04 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant demandé en FCFA')),
                ('duration_months', models.PositiveSmallIntegerField(default=6)),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='monthly', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('in_review', 'En analyse'), ('approved', 'Approuvée'), ('disbursed', 'Décaissée'), ('rejected', 'Rejetée')], default='submitted', max_length=20)),
                ('eligibility_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_credits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='credit_documents/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='microcredits.creditapplication')),
            ],
        ),
    ]
