# Generated by Django 5.2.15 on 2026-06-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='creditapplication',
            name='repayment_frequency',
        ),
        migrations.RemoveField(
            model_name='creditdocument',
            name='label',
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Soumise'), ('in_review', 'En analyse'), ('approved', 'Approuvée'), ('disbursed', 'Décaissée')], default='submitted', max_length=20),
        ),
    ]
